---
title: "Final Project"
author: "Abby Englebert"
date: "2024-03-09"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Proposal
***Section 1 - Introduction***

In this dataset we will be looking at how different movie trailers on youtube over the last couple of decades have impacted the success of the film themselves. The dataset I found was off of **https://www.kaggle.com**, and the data was collected by "CinemaFuture, a machine learning project focused on predicting the potential success of films." The tool searches for box office earnings, budgets, cast and crew information, genres, release dates, audience ratings, and social media trends, however in this specific it scrapes YouTube comments from upcoming movies' trailers and conducts sentiment analysis to predict the success of the movie(s).

***Section 2 - Data***

See the '/data' foler.

***Section 3 - Data Analysis Plan***    

– The outcome (response, Y) and predictor (explanatory, X) variables you will use to answer your question.

*The outcome is 'Gross', the predictor is 'Sentiment Scores'.*

– Very preliminary exploratory data analysis, including some summary statistics and visualizations, along with some explanation on how they help you learn more about your data. (You can add to these later as you work on your project.)


#| label: movies_youtube_sentiments-skim

skim(movies_youtube_sentiments)



– The method(s) that you believe will be useful in answering your question(s). (You can update these later as you work on your project.)

*I would create a multitude of different graphs that are able to display the specific data I need.*

– What results from these specific statistical methods are needed to support your hypothesized answer?

*The results I would need would be showing the difference between the gross or rating of a film that has a trailer on youtube, versus one that doesnt have a trailer on youtube.*